---
sudo: required

dist: bionic

env:
  - BUILDER=packer PATH_TO_BUILDSCRIPT=packer-build BUILDSCRIPT=devopsubuntu1804.json

before_script:
  - sudo apt-get update

script:

  - sudo $BUILDER --version
  - cd $PATH_TO_BUILDSCRIPT
  - sudo $BUILDER validate $BUILDSCRIPT
