- name: Playbook to Install Git
  hosts: localhost  ## For running the playbook on localhost system.
  become: yes
  connection: local ## Runs the playbook locally. Change to ssh if required to run on other instances.
  gather_facts: no
  tasks:
  - name: Update Repository cache
    apt:
      update_cache: yes
  - name: Install Git
    apt:
      name: git
      state: latest
      force_apt_get: yes
      autoclean: yes
      autoremove: yes
