- hosts: localhost  ## For running the playbook on localhost system.
  become: yes
  connection: local ## Runs the playbook locally. Change to ssh if required to run on other instances.
  gather_facts: no
  tasks:
  - name: Update Repository cache
    apt:
      update_cache: yes
  - name: Install Python3
    apt:
      name: python3
      state: latest
      force_apt_get: yes
      autoclean: yes
      autoremove: yes
