- hosts: local
  become: yes
  gather_facts: no
  tasks:
  - name: Install Python3-pip
    apt:
      name: python3-pip
      state: latest
      force_apt_get: yes
      autoclean: yes
      autoremove: yes
  - name: Upgrade pip of python3 to latest.
    pip:
      name: pip
      state: latest
      executable: pip3
