- name: Playbook to Install Ruby
  hosts: localhost  ## For running the playbook on localhost system.
  become: yes
  connection: local ## Runs the playbook locally. Change to ssh if required to run on other instances.
  gather_facts: no
  tasks:
  - name: Update Repository cache
    apt:
      update_cache: yes
  - name: Install Ruby
    apt:
      name: ruby
      state: latest
      force_apt_get: yes
      autoclean: yes
      autoremove: yes
  - name: Check ruby version
    shell: ruby --version
    args:
      executable: /bin/bash
    register: ruby_version
  - name: Install serverspec
    shell: gem install serverspec
    args:
      executable: /bin/bash
  - name: Print Ruby's version
    debug:
      var: ruby_version.stdout